namespaces:
    CCDNMessageMessageBundle: CCDNMessage\MessageBundle\Form\Validator\Constraints\

CCDNMessage\MessageBundle\Entity\Message:
    properties:
        sendTo:
            - Type: string
            - NotBlank: ~
            - MaxLength: { limit: 255 }
            - "CCDNMessageMessageBundle:SendTo": ~
        subject:
            - Type: string
            - NotBlank: ~
            - MinLength: { limit: 2 }
            - MaxLength: { limit: 255 }
        body:
            - Type: string
            - NotBlank: ~
            - MinLength: { limit: 5 }
            - MaxLength: { limit: 5000 }
        isFlagged:
            - Type: bool
            - NotNull: ~
